---
apiVersion: dpc.dell.com/v1alpha1
kind: ManagedNode
metadata:
  name: dell-r760-node01
  namespace: default
spec:
  membership: Present
status:
  conditions:
    - lastTransitionTime: "2026-01-08T06:00:00Z"
      message: "Node is healthy and all components are operational"
      reason: AllComponentsHealthy
      status: "True"
      type: Healthy
    - lastTransitionTime: "2026-01-08T06:00:00Z"
      message: "Node is ready for workloads"
      reason: NodeReady
      status: "True"
      type: Ready
  inventory:
    system_info:
      bios_version: "2.10.2"
      manufacturer: "Dell Inc."
      model: "PowerEdge R760"
      serial_number: "ABCD123"
    cpu:
      cores: 32
      model: "Intel Xeon Gold 6430"
      speed_mhz: 2100
      threads: 64
    memory:
      speed_mhz: 4800
      total_gb: 512
      type: "DDR5"
    cooling:
      fans:
        - fqdd: "Fan.Embedded.1"
          rpm: 8500
          status: "OK"
        - fqdd: "Fan.Embedded.2"
          rpm: 8600
          status: "OK"
        - fqdd: "Fan.Embedded.3"
          rpm: 8400
          status: "OK"
        - fqdd: "Fan.Embedded.4"
          rpm: 8550
          status: "OK"
    power:
      psus:
        - fqdd: "PSU.Slot.1"
          input_watts: "750"
          status: "OK"
        - fqdd: "PSU.Slot.2"
          input_watts: "750"
          status: "OK"
    storage:
      controllers:
        - "RAID.Integrated.1-1"
      drives:
        - capacity_bytes: 960000000000
          fqdd: "Disk.Bay.0:Enclosure.Internal.0-1"
          slot_index: 0
          status: "OK"
          type: "SSD"
        - capacity_bytes: 960000000000
          fqdd: "Disk.Bay.1:Enclosure.Internal.0-1"
          slot_index: 1
          status: "OK"
          type: "SSD"
        - capacity_bytes: 4000000000000
          fqdd: "Disk.Bay.2:Enclosure.Internal.0-1"
          slot_index: 2
          status: "OK"
          type: "HDD"
        - capacity_bytes: 4000000000000
          fqdd: "Disk.Bay.3:Enclosure.Internal.0-1"
          slot_index: 3
          status: "OK"
          type: "HDD"
    network:
      adapters:
        - fqdd: "NIC.Integrated.1-1"
          description: "Broadcom Gigabit Ethernet"
          mac_address: "00:1A:2B:3C:4D:01"
          speed_gbps: 1
          status: "OK"
          type: "Ethernet"
        - fqdd: "NIC.Slot.2-1"
          description: "Intel X710 10GbE"
          mac_address: "00:1A:2B:3C:4D:02"
          speed_gbps: 10
          status: "OK"
          type: "Ethernet"
  lastCollectedAt: "2026-01-08T06:30:00Z"
  source: "idrac"
---
apiVersion: dpc.dell.com/v1alpha1
kind: ManagedNode
metadata:
  name: dell-r760-node02
  namespace: default
spec:
  membership: Present
status:
  conditions:
    - lastTransitionTime: "2026-01-08T05:45:00Z"
      message: "Fan.Embedded.2 is running at degraded speed"
      reason: ComponentDegraded
      status: "False"
      type: Healthy
    - lastTransitionTime: "2026-01-08T05:45:00Z"
      message: "Node is ready but with warnings"
      reason: NodeReady
      status: "True"
      type: Ready
  inventory:
    system_info:
      bios_version: "2.10.2"
      manufacturer: "Dell Inc."
      model: "PowerEdge R760"
      serial_number: "EFGH456"
    cpu:
      cores: 32
      model: "Intel Xeon Gold 6430"
      speed_mhz: 2100
      threads: 64
    memory:
      speed_mhz: 4800
      total_gb: 256
      type: "DDR5"
    cooling:
      fans:
        - fqdd: "Fan.Embedded.1"
          rpm: 8500
          status: "OK"
        - fqdd: "Fan.Embedded.2"
          rpm: 3200
          status: "Warning"
        - fqdd: "Fan.Embedded.3"
          rpm: 8400
          status: "OK"
        - fqdd: "Fan.Embedded.4"
          rpm: 8550
          status: "OK"
    power:
      psus:
        - fqdd: "PSU.Slot.1"
          input_watts: "750"
          status: "OK"
        - fqdd: "PSU.Slot.2"
          input_watts: "750"
          status: "OK"
    storage:
      controllers:
        - "RAID.Integrated.1-1"
      drives:
        - capacity_bytes: 960000000000
          fqdd: "Disk.Bay.0:Enclosure.Internal.0-1"
          slot_index: 0
          status: "OK"
          type: "SSD"
        - capacity_bytes: 960000000000
          fqdd: "Disk.Bay.1:Enclosure.Internal.0-1"
          slot_index: 1
          status: "OK"
          type: "SSD"
    network:
      adapters:
        - fqdd: "NIC.Integrated.1-1"
          description: "Broadcom Gigabit Ethernet"
          mac_address: "00:1A:2B:3C:4D:11"
          speed_gbps: 1
          status: "OK"
          type: "Ethernet"
  lastCollectedAt: "2026-01-08T06:25:00Z"
  source: "idrac"
---
apiVersion: dpc.dell.com/v1alpha1
kind: ManagedNode
metadata:
  name: dell-r660-node03
  namespace: default
spec:
  membership: Present
status:
  conditions:
    - lastTransitionTime: "2026-01-08T06:10:00Z"
      message: "Node is healthy and all components are operational"
      reason: AllComponentsHealthy
      status: "True"
      type: Healthy
    - lastTransitionTime: "2026-01-08T06:10:00Z"
      message: "Node is ready for workloads"
      reason: NodeReady
      status: "True"
      type: Ready
  inventory:
    system_info:
      bios_version: "1.8.1"
      manufacturer: "Dell Inc."
      model: "PowerEdge R660"
      serial_number: "IJKL789"
    cpu:
      cores: 24
      model: "Intel Xeon Silver 4410Y"
      speed_mhz: 2000
      threads: 48
    memory:
      speed_mhz: 4400
      total_gb: 128
      type: "DDR5"
    cooling:
      fans:
        - fqdd: "Fan.Embedded.1"
          rpm: 7800
          status: "OK"
        - fqdd: "Fan.Embedded.2"
          rpm: 7900
          status: "OK"
    power:
      psus:
        - fqdd: "PSU.Slot.1"
          input_watts: "600"
          status: "OK"
        - fqdd: "PSU.Slot.2"
          input_watts: "600"
          status: "OK"
    storage:
      controllers:
        - "RAID.Integrated.1-1"
      drives:
        - capacity_bytes: 480000000000
          fqdd: "Disk.Bay.0:Enclosure.Internal.0-1"
          slot_index: 0
          status: "OK"
          type: "SSD"
        - capacity_bytes: 480000000000
          fqdd: "Disk.Bay.1:Enclosure.Internal.0-1"
          slot_index: 1
          status: "OK"
          type: "SSD"
    network:
      adapters:
        - fqdd: "NIC.Integrated.1-1"
          description: "Broadcom Gigabit Ethernet"
          mac_address: "00:1A:2B:3C:4D:21"
          speed_gbps: 1
          status: "OK"
          type: "Ethernet"
  lastCollectedAt: "2026-01-08T06:28:00Z"
  source: "idrac"
---
apiVersion: dpc.dell.com/v1alpha1
kind: ManagedNode
metadata:
  name: dell-r760-node04
  namespace: default
spec:
  membership: Present
status:
  conditions:
    - lastTransitionTime: "2026-01-08T04:00:00Z"
      message: "PSU.Slot.2 has failed"
      reason: ComponentFailed
      status: "False"
      type: Healthy
    - lastTransitionTime: "2026-01-08T04:00:00Z"
      message: "Node is running with degraded power redundancy"
      reason: NodeDegraded
      status: "True"
      type: Ready
  inventory:
    system_info:
      bios_version: "2.10.2"
      manufacturer: "Dell Inc."
      model: "PowerEdge R760"
      serial_number: "MNOP012"
    cpu:
      cores: 32
      model: "Intel Xeon Gold 6430"
      speed_mhz: 2100
      threads: 64
    memory:
      speed_mhz: 4800
      total_gb: 512
      type: "DDR5"
    cooling:
      fans:
        - fqdd: "Fan.Embedded.1"
          rpm: 9500
          status: "OK"
        - fqdd: "Fan.Embedded.2"
          rpm: 9600
          status: "OK"
        - fqdd: "Fan.Embedded.3"
          rpm: 9400
          status: "OK"
        - fqdd: "Fan.Embedded.4"
          rpm: 9550
          status: "OK"
    power:
      psus:
        - fqdd: "PSU.Slot.1"
          input_watts: "750"
          status: "OK"
        - fqdd: "PSU.Slot.2"
          input_watts: "0"
          status: "Critical"
    storage:
      controllers:
        - "RAID.Integrated.1-1"
      drives:
        - capacity_bytes: 1920000000000
          fqdd: "Disk.Bay.0:Enclosure.Internal.0-1"
          slot_index: 0
          status: "OK"
          type: "NVMe"
        - capacity_bytes: 1920000000000
          fqdd: "Disk.Bay.1:Enclosure.Internal.0-1"
          slot_index: 1
          status: "OK"
          type: "NVMe"
        - capacity_bytes: 1920000000000
          fqdd: "Disk.Bay.2:Enclosure.Internal.0-1"
          slot_index: 2
          status: "OK"
          type: "NVMe"
        - capacity_bytes: 1920000000000
          fqdd: "Disk.Bay.3:Enclosure.Internal.0-1"
          slot_index: 3
          status: "OK"
          type: "NVMe"
    network:
      adapters:
        - fqdd: "NIC.Integrated.1-1"
          description: "Broadcom Gigabit Ethernet"
          mac_address: "00:1A:2B:3C:4D:31"
          speed_gbps: 1
          status: "OK"
          type: "Ethernet"
        - fqdd: "NIC.Slot.2-1"
          description: "Intel X710 10GbE"
          mac_address: "00:1A:2B:3C:4D:32"
          speed_gbps: 10
          status: "OK"
          type: "Ethernet"
        - fqdd: "NIC.Slot.3-1"
          description: "Mellanox ConnectX-6 25GbE"
          mac_address: "00:1A:2B:3C:4D:33"
          speed_gbps: 25
          status: "OK"
          type: "Ethernet"
  lastCollectedAt: "2026-01-08T06:20:00Z"
  source: "idrac"
